### ISSUE TITLE
The provided "crb" data seems to be incomplete.

### ISSUE THREAD

**Issue by LinLin1031** [ouenal/scribblekitti#11]
Hello!

When I was experimenting with the provided crb (https://data.vision.ee.ethz.ch/ouenal/scribblekitti/crb.zip), I found that two label files are missing from sequence 09, which are "000061.label" and "001455.label". Is this a a mistake? I hope you can provide the complete file again at your convenience, thank you.

Best.

**Comment by ouenal** [comment]
Thanks for reporting the issue, I'm assuming the data was corrupted somehow. I will generate the labels over the weekend and reupload them. If you don't want to wait, you can also run step 2 using the checkpoint from step 1.
