### ISSUE TITLE
Where can I find the model files for MinkowskiNet and SPVCNN?

### ISSUE THREAD

**Issue by zhairf** [ouenal/scribblekitti#13]
Thanks for your amazing work. 

In your paper, you mentioned that the algorithm was tested using Cylinder3D, MinkowskiNet, and SPVCNN, but I only found the code for the Cylinder3D. Could you please provide the code for the other two segmentation models? 

Thank you.

**Comment by ouenal** [comment]
I never integrated the two other models into this repository so I can't release a version like that. To run SSLSS with the other two models, I simply integrated the MT/PLS dataloaders and the mean teacher pipeline into the [spvnas  repository](https://github.com/mit-han-lab/spvnas) at the time.
Hope that helps.

**Comment by zhairf** [comment]
Thank you very much for your explanation.
